# Generated by Django 5.2.5 on 2025-08-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="post_type",
            field=models.CharField(
                choices=[("image", "图文"), ("video", "视频")],
                default="image",
                max_length=10,
                verbose_name="帖子类型",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="notes_videos/",
                verbose_name="视频文件",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="videos_thumbnails/",
                verbose_name="视频封面",
            ),
        ),
    ]
