# Generated by Django 5.2.5 on 2025-08-13 22:25

import xiaohongshu_backend.core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_post_type_note_video_note_video_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                storage=xiaohongshu_backend.core.storages.PublicMediaStorage(),
                upload_to="notes_videos/",
                verbose_name="视频文件",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=xiaohongshu_backend.core.storages.PublicMediaStorage(),
                upload_to="videos_thumbnails/",
                verbose_name="视频封面",
            ),
        ),
    ]
