# Generated by Django 5.2.5 on 2025-08-15 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="被举报对象ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "垃圾广告"),
                            ("inappropriate", "不当内容"),
                            ("hate_speech", "仇恨言论"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="举报理由",
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="详细信息"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("action_taken", "已处理"),
                            ("no_action", "已忽略"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="举报时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="被举报内容类型",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="举报人",
                    ),
                ),
            ],
            options={
                "verbose_name": "举报",
                "verbose_name_plural": "举报",
                "ordering": ["-created_at"],
                "unique_together": {("reporter", "content_type", "object_id")},
            },
        ),
    ]
